# -*- coding: utf-8 -*-
"""AULA4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ueseNKSK43oYvZDmtaQuNXvbIOnfa2de
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np

img = cv2.imread("melancia.png")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

image_lower_hsv = np.array([0, 100, 210])
image_upper_hsv = np.array([180, 200, 255])

mask_hsv = cv2.inRange(img_hsv, image_lower_hsv, image_upper_hsv)

plt.imshow(img_rgb)
plt.show()
plt.imshow(mask_hsv, cmap="gray")

contornos, _ = cv2.findContours(mask_hsv, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
mask_rgb = cv2.cvtColor(mask_hsv, cv2.COLOR_GRAY2RGB)

contornos_img = mask_rgb.copy()

cv2.drawContours(contornos_img, contornos, -1, [0, 255, 0], 5)
                                          #-1 exibe o contorna da imagem toda
                                          # o do meio é cor
                                          #5 é a espessura do contorno
plt.imshow(contornos_img)

print("quantidade de contornos: ", len(contornos))

img_bolinha = cv2.imread("bolinha.png")
img_rgb = cv2.cvtColor(img_bolinha, cv2.COLOR_BGR2RGB)
img_hsv = cv2.cvtColor(img_bolinha, cv2.COLOR_RGB2HSV)

image_lower_hsv = np.array([130, 50, 200])
image_upper_hsv = np.array([150, 255, 255])

mask_hsv = cv2.inRange(img_hsv, image_lower_hsv, image_upper_hsv)

plt.imshow(img_rgb)
plt.show()
plt.imshow(mask_hsv, cmap="gray")

contornos, _ = cv2.findContours(mask_hsv, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
mask_rgb = cv2.cvtColor(mask_hsv, cv2.COLOR_GRAY2RGB)

contornos_img = mask_rgb.copy()

cv2.drawContours(contornos_img, contornos, -1, [0, 255, 0], 5)
                                          #-1 exibe o contorna da imagem toda
                                          # o do meio é cor
                                          #5 é a espessura do contorno
plt.imshow(contornos_img)

print("quantidade de contornos: ", len(contornos))

